version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: wordapp_db
    environment:
      POSTGRES_USER: worduser
      POSTGRES_PASSWORD: wordpass123
      POSTGRES_DB: wordapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U worduser -d wordapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: wordapp_backend
    environment:
      DATABASE_URL: postgresql://worduser:wordpass123@db:5432/wordapp
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    image: nginx:alpine
    container_name: wordapp_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
